### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rahulvaish**
Fixed the broken image in README.md

### CODE REVIEW

**Comment by quozl** [comment]
Unfortunately the link is not relative to a file in the repository, so when the repository is cloned and the README.md is viewed the image is not loaded from the clone.

**Comment by rahulvaish** [comment]
To understand  -  Do we want the user to click on 'alt text' (on READMe.md) and view the image on the new tab ? or present the image on README.md (on page load)?

**Comment by rahulvaish** [comment]
As a demo, I have created a dummy file (in my personal repo) showcasing both the presentation style:
https://github.com/rahulvaish/ReferenceDocuments/blob/master/README.md

**Comment by quozl** [comment]
No, you misunderstand.  Look at the markdown text in the [raw file](https://raw.githubusercontent.com/rahulvaish/ReferenceDocuments/master/README.md).  You'll see a link to something outside the repository.

```
Based on the pytagcloud package.
![image](https://user-images.githubusercontent.com/689226/85977720-bb168800-b9fa-11ea-8ffe-919d279a8952.png)
```

Now look at the markdown text of, to choose a random example, this file; https://github.com/sugarlabs/GSoC/blob/master/README.md

```
<a href="Ideas-2020.md">![](assets/gsoc-square.png)</a> 
```

See how the markdown text links cleanly to the file in the repository, and not to some randomly generated temporary URL.

**Comment by rahulvaish** [comment]
Understood!

Do you want me to keep the .png as a separate file in the repo and link it with the README.md? **If you allow, and if that is required, I can do it now !!**


Actually, there are different ways to put images on README.md. The URL placed is not a temporary URL. How it works is:
- Open the GitHub repository.
- Click on "Issues"
- Click on the  "New Issue" button.
- In the description box, paste the image. The image gets uploaded on Github (upload time may depend on the internet speed), and then, GitHub itself generates a URL for you to use anywhere. (preferably in the README.md).
- The approach is adopted widely because you don't need any additional file/s to place in your repo and do linkings. This is an automated feature/approach form the GitHub Team themselves.

**Comment by srevinsaju** [comment]
I am not understanding. Why do you want to go in a completely overly complicated path of adding an image to the README.md and not using the relative path to the image. I understand the method you are trying to implement, but thats not the best mesthod.

```
![alt text here](/relative/path/to/image/with/respect/to/the/README/file.png)
```

**Comment by rahulvaish** [comment]
Okay. I shall close the PR then.

**Comment by quozl** [comment]
Yes, please include the PNG image as a separate file in the repository, as I demonstrated.

We do it that way so that;
* the markdown reference continues to work in a clone,
* the clone contains everything contributed,
* the image is under change control and has a history,
* we can avoid GitHub and use GitLab or something else later.

Also, be aware that issues and pull requests are not eternal.  They are eventually archived.  When that happens, the temporary link does break.  We've had that happen before, which is why we're sensitive to you doing it.  It's not about you.  :grin:

**Pull request closed without merging**
